import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarProvider } from "@/context/SidebarContext";
import SessionProvider from "@/components/SessionProvider";
import ProtectedRoute from "@/components/ProtectedRoute";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Daily Productivity",
  description: "Generated by create next app",
};

export default function ProtectedLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProtectedRoute>
          <SidebarProvider>
            <SessionProvider>
              {children}
            </SessionProvider>
          </SidebarProvider>
        </ProtectedRoute>
      </body>
    </html>
  );
}
